= TeXBibXML
:nofooter:

TeXBibXML is a recursive descent parser in Ruby that parses TeX bibliography
into an abstract syntax tree (AST) in XML. It offers the ability to use a
custom parser for any field of a TeX bibliography entry. TeXBibXML includes a
separate parser for parsing TeX with the similar ability to accept custom
parsers for specific TeX commands.

== Building

Build and install to the user directory as a gem with

----
gem build texbibxml.gemspec
gem install --user-install texbibxml-<version>.gem
----

where `<version>` is the version of the gem. Executable is provided at
`bin/texbibxml` under where the gem is installed. The gem can be uninstalled by

----
gem uninstall --user-install texbibxml
----

Tests can be run with

----
rake test
----

== Usage

TeXBibXML can be used as a command-line application or as a library.

=== Application

To use TeXBibXML as a command-line application for parsing a TeX bibliography
file, `references.bib`, with pretty printing using `xmllint`,

----
texbibxml <references.bib | xmllint --format -
----

`texbibxml` executable reads only from standard input and does not take
command-line arguments.

=== Library

To use TeXBibXML as a Ruby library for generating the AST of a TeX bibliography
input,

----
require "texbibxml"
texbib = <<'EOF'
@article{
  bjorck-1994,
  author = "Bj{\"{o}}rck, {\r{A}}",
  title = {Numerics of Gram-Schmidt Orthogonalization},
  journal = {Linear Algebra and its Applications},
  year = "1994",
  volume = "197--198",
  pages = "297--316"
}
@article{
  west-2014,
  author = "West, Aaron",
  title = {Weighted orthogonalization of atomic orbitals: A stable alternative to the Carlson-Keller method},
  journal = {Computational and Theoretical Chemistry},
  year = "2014",
  volume = "1045",
  pages = "73--77"
}
EOF
texbib_parser = Texbibxml::Tex::Bib::Parser.new
my_texbib_ast = texbib_parser.parse(texbib)
my_texbib_ast.write
----

Pretty-printed output (via `xmllint` on the command line) of the XML document
in the variable, `my_texbib_ast`, would be

----
<?xml version="1.0" encoding="UTF-8"?>
<texbib>
  <entry xml:id="bjorck-1994" type="article">
    <author>Bj{\"{o}}rck, {\r{A}}</author>
    <title>Numerics of Gram-Schmidt Orthogonalization</title>
    <journal>Linear Algebra and its Applications</journal>
    <year>1994</year>
    <volume>197--198</volume>
    <pages>297--316</pages>
  </entry>
  <entry xml:id="west-2014" type="article">
    <author>West, Aaron</author>
    <title>Weighted orthogonalization of atomic orbitals: A stable alternative to the Carlson-Keller method</title>
    <journal>Computational and Theoretical Chemistry</journal>
    <year>2014</year>
    <volume>1045</volume>
    <pages>73--77</pages>
  </entry>
</texbib>
----

The above output is simpler than the output from using the `texbibxml`
executable since the executable passes a dedicated parser of the `author` field
to the constructor of `Texbibxml::Tex::Bib::Parser`. Included in TeXBibXML, the
parser of the `author` field separates the authors into their own `member`
element and subdivides the name of each author to `surname` and `first-name`
elements.

Suppose John Doe and Jane Doe are authors of a fictional article in TeX
bibliography:

----
@article{
  doe-2023,
  author = "Doe, John and Jane Doe",
  title = {The Doe Legacy},
  journal = {Doe Publishing},
  year = "2023",
  volume = "1",
  pages = "1--10"
}
----

Assuming this entry is read from standard input, the Ruby code to parse such an
entry with additional parsing of the `author` field could be

----
require "texbibxml"
texbib_author_parser = Texbibxml::Tex::Bib::Author::Parser.new
texbib_parser = Texbibxml::Tex::Bib::Parser.new(
  "author" => lambda do |_, field_value, entry_ast|
    texbib_author_parser.append_ast(field_value, entry_ast)
  end
)
doe_texbib_ast = texbib_parser.parse(STDIN.readlines.join(""))
doe_texbib_ast.write
----

Pretty-printed output of `doe_texbib_ast` would be

----
<?xml version="1.0" encoding="UTF-8"?>
<texbib>
  <entry xml:id="doe-2023" type="article">
    <author>
      <member>
        <surname>Doe</surname>
        <first-name>John</first-name>
      </member>
      <member>
        <surname>Doe</surname>
        <first-name>Jane</first-name>
      </member>
    </author>
    <title>The Doe Legacy</title>
    <journal>Doe Publishing</journal>
    <year>2023</year>
    <volume>1</volume>
    <pages>1--10</pages>
  </entry>
</texbib>
----

When the parser of the `author` field is used, the `author` element in the
resulting AST has the two authors separated with their respective surname and
first name properly determined regardless of how their names are formatted in
the TeX bibliography.

== Documentation

Documentation can be generated by

----
yard doc -m markdown --protected --private -o target/site/apidocs
----

It is also available at https://hc1839.github.io/texbibxml/apidocs/.
